import type { Metadata } from "next";
import "./../public/css/globals.css";
import "./../public/css/fonts.css";
import Header from "./../components/common/header";
import AppProvider from "@/core/providers/app-provider";

export const metadata: Metadata = {
  title: "کانسپتو - بهترین کمپانی برای شما",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <AppProvider>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
