import type { Metadata } from "next";
import "./../public/css/globals.css";
import "./../public/css/fonts.css";
import Header from "./../components/common/header";


export const metadata: Metadata = {
  title: "کانسپتو - بهترین کمپانی برای شما",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
